updated menu to have correct buttons, and added actions for stop and start

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -73,5 +73,6 @@ jobs:
         run: |
           echo "executing tests"
           cd build || exit
-          pytest || { echo "tests failed, exiting" ; exit 1; }
+          coverage run --rcfile='../.coveragerc' -m pytest || { echo "tests failed, exiting" ; exit 1; }
+          coverage report --rcfile='../.coveragerc' || exit 1
           cd .. || exit
diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # clean build folder
-./clean.sh
+./clean
 
 # copy files into build folder
 for D in src/lambda/*; do
@@ -23,5 +23,7 @@ done
 
 echo "executing tests"
 cd build || exit
-pytest || { echo "tests failed, exiting" ; exit 1; }
+coverage run --rcfile='../.coveragerc' -m pytest || { echo "tests failed, exiting" ; exit 1; }
+coverage html
+coverage report --rcfile='../.coveragerc' || exit 1
 cd .. || exit
